import 'css/tailwind.css'
import 'remark-github-blockquote-alert/alert.css'

import { Space_Grotesk } from 'next/font/google'
import { Analytics, AnalyticsConfig } from 'pliny/analytics'
import Header from '@/components/Header'
import SectionContainer from '@/components/SectionContainer'
import Footer from '@/components/Footer'
import PageTransition from '@/components/PageTransition'
import ScrollProgress from '@/components/ScrollProgress'
import ScrollToTop from '@/components/ScrollToTop'
import siteMetadata from '@/data/siteMetadata'
import { ThemeProviders } from './theme-providers'
import { Metadata } from 'next'

const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  metadataBase: new URL(siteMetadata.siteUrl),
  title: {
    default: siteMetadata.title,
    template: `%s | ${siteMetadata.title}`,
  },
  description: siteMetadata.description,
  openGraph: {
    title: siteMetadata.title,
    description: siteMetadata.description,
    url: './',
    siteName: siteMetadata.title,
    locale: 'en_US',
    type: 'website',
  },
  alternates: {
    canonical: './',
    types: {
      'application/rss+xml': `${siteMetadata.siteUrl}/feed.xml`,
    },
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  twitter: {
    title: siteMetadata.title,
    card: 'summary_large_image',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const basePath = process.env.BASE_PATH || ''

  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Person',
        '@id': `${siteMetadata.siteUrl}/#person`,
        name: 'Youssef Bastawisy',
        url: siteMetadata.siteUrl,
        image: `${siteMetadata.siteUrl}/static/images/avatar2.jpg`,
        jobTitle: 'AI Engineer',
        worksFor: {
          '@type': 'Organization',
          name: 'Cycls',
        },
        sameAs: [
          siteMetadata.linkedin,
          siteMetadata.github,
          siteMetadata.email ? `mailto:${siteMetadata.email}` : '',
        ],
        knowsAbout: [
          'Agentic AI',
          'Multi-Agent Orchestration',
          'Retrieval-Augmented Generation',
          'Large Language Models',
          'Function Calling & Tool Use',
          'Structured Outputs',
          'Machine Learning',
          'Natural Language Processing',
          'Python',
          'MLOps',
        ],
        alumniOf: {
          '@type': 'CollegeOrUniversity',
          name: 'Pharos University in Alexandria',
        },
      },
      {
        '@type': 'WebSite',
        '@id': `${siteMetadata.siteUrl}/#website`,
        name: siteMetadata.title,
        url: siteMetadata.siteUrl,
        description: siteMetadata.description,
        inLanguage: 'en-US',
        publisher: { '@id': `${siteMetadata.siteUrl}/#person` },
      },
    ],
  }

  return (
    <html
      lang={siteMetadata.language}
      className={`${space_grotesk.variable} scroll-smooth`}
      suppressHydrationWarning
    >
      <head>
        {/* Favicons are generated by app/icon.tsx and app/apple-icon.tsx */}
        <meta name="msapplication-TileColor" content="#4f46e5" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#0a0a0a" />
        <link rel="alternate" type="application/rss+xml" href={`${basePath}/feed.xml`} />

        {/* Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />

        {/* Additional SEO Meta Tags */}
        <meta name="author" content="Youssef Bastawisy" />
        <meta
          name="keywords"
          content="AI Engineer, Agentic AI, LLMs, RAG, Multi-Agent Systems, Function Calling, Machine Learning, NLP, Python, LLMOps"
        />
      </head>
      <body className="overflow-x-hidden bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
        <ThemeProviders>
          <ScrollProgress />
          <ScrollToTop />
          <Analytics analyticsConfig={siteMetadata.analytics as AnalyticsConfig} />
          <SectionContainer>
            <Header />
            <main className="relative z-10 mb-auto overflow-hidden">
              <PageTransition>{children}</PageTransition>
            </main>
            <Footer />
          </SectionContainer>
        </ThemeProviders>
      </body>
    </html>
  )
}
